[Paths]
Prefix = /Users/roman/projects/bsu/PKG/ItteC/winbuild/qt/6.11.0/mingw_64
Binaries = /Users/roman/Qt/6.11.0/macos/bin
LibraryExecutables = /Users/roman/Qt/6.11.0/macos/libexec
Data = /Users/roman/projects/bsu/PKG/ItteC/winbuild/qt/6.11.0/mingw_64
